version: "3.8"

services:
  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    networks:
      - excalibur_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h database"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - excalibur_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  excalibur:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        if [ $ENVIRONMENT = 'production' ]; then
          gunicorn excalibur.wsgi:application --bind 0.0.0.0:8000 --timeout 180 --log-level debug;
        else
          python manage.py runserver 0.0.0.0:8000;
        fi
      "
    volumes:
      - ./apps/facture:/usr/src/app/apps/facture
      - ./apps/deduction:/usr/src/app/apps/deduction
      - ./apps/users:/usr/src/app/apps/users
      - ./apps/main:/usr/src/app/apps/main
      - ./excalibur:/usr/src/app/excalibur
      - static_volume:/var/www/staticfiles  # This is where the static files will be stored
      - media_volume:/usr/src/app/media
    restart: always
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=excalibur.settings
      - ENVIRONMENT=${ENVIRONMENT:-development}  # Default to 'development' if ENVIRONMENT is not set
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/facture/local/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - excalibur_network
    working_dir: /usr/src/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - excalibur
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - excalibur_network
    volumes:
      - ./nginx/html:/var/www/html  # For Let's Encrypt challenges
      - ./nginx/ssl:/etc/nginx/ssl  # For SSL certificates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email ibhayk@gmail.com --agree-tos --no-eff-email -d pmsolution-facture.org -d www.pmsolution-facture.org
    depends_on:
      - nginx

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  excalibur_network:
    driver: bridge
