# Generated by Django 5.1.4 on 2024-12-19 15:33

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('number_facture', models.CharField(default=2024, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('firm_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2024, 12, 19))),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                (
                    'percent',
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ('quantity_after_percent', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('net_pay', models.FloatField()),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LocalFacture',
            fields=[
                (
                    'facture_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='facture.facture',
                    ),
                ),
                ('destination', models.CharField(default='Recharge express', max_length=255)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('tax_ht', models.FloatField()),
                ('total_ttc', models.FloatField()),
                ('total_sum_fr', models.CharField(max_length=255)),
            ],
            bases=('facture.facture',),
        ),
        migrations.CreateModel(
            name='WorldFacture',
            fields=[
                (
                    'facture_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='facture.facture',
                    ),
                ),
                ('account_number', models.IntegerField()),
                ('receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('sku', models.IntegerField(blank=True, null=True)),
                (
                    'description',
                    models.CharField(default='Recharge Card and Express', max_length=255),
                ),
                ('specification', models.IntegerField(blank=True, null=True)),
                ('shipping_fee', models.FloatField(blank=True, null=True)),
                ('total_sum_en', models.CharField(max_length=255)),
            ],
            bases=('facture.facture',),
        ),
    ]
