# Generated by Django 5.1 on 2024-08-11 19:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_facture', models.IntegerField(default=2024)),
                ('firm_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('facture_type', models.CharField(choices=[('internal', 'Internal'), ('world', 'World')], max_length=10)),
                ('update_time', models.DateField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=10)),
                ('destination', models.CharField(default='Recharge Express', max_length=30)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quantity_after_percent', models.FloatField(blank=True, null=True)),
                ('advance_payment', models.CharField(blank=True, default='', max_length=10)),
                ('total_tax', models.FloatField(blank=True, null=True)),
                ('total_payment_after_tax', models.FloatField(blank=True, null=True)),
                ('total_sum_fr', models.TextField()),
                ('total_sum_en', models.TextField()),
                ('contract_date', models.CharField(max_length=25)),
                ('account_number', models.CharField(blank=True, max_length=25, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
