# Generated by Django 5.1 on 2024-11-05 16:29

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('number_facture', models.IntegerField(default=2024)),
                ('date', models.DateField(default=datetime.date(2024, 11, 5))),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                ('percent', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quantity_after_percent', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('total_payment_after_tax', models.FloatField()),
                ('facture_type', models.CharField(choices=[('local', 'Local'), ('world', 'World')], default='local', max_length=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFacture',
            fields=[
                ('facture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facture.facture')),
                ('identification_number', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(default='Recharge express', max_length=255)),
                ('deposit', models.FloatField(blank=True, null=True)),
            ],
            bases=('facture.facture',),
        ),
        migrations.CreateModel(
            name='WorldFacture',
            fields=[
                ('facture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facture.facture')),
                ('firm_name', models.TextField()),
                ('account_number', models.IntegerField()),
                ('sku', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('specification', models.IntegerField(blank=True, null=True)),
            ],
            bases=('facture.facture',),
        ),
    ]
