# Generated by Django 5.1 on 2024-11-27 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='facture_type',
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 27)),
        ),
    ]
