# Generated by Django 5.1.4 on 2024-12-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('fr', 'French')],
                default='en',
                max_length=10,
            ),
        ),
    ]
