# Generated by Django 5.1 on 2024-11-28 00:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 28)),
        ),
        migrations.AlterField(
            model_name='facture',
            name='number_facture',
            field=models.CharField(default=2024),
        ),
    ]
