# Generated by Django 5.1.4 on 2024-12-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0002_facture_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='language',
        ),
    ]
