# Generated by Django 5.1 on 2024-11-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0003_alter_facture_date_alter_facture_number_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='number_facture',
            field=models.CharField(default=2024, unique=True),
        ),
    ]
