# Generated by Django 5.1 on 2024-12-11 16:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0004_alter_facture_number_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfacture',
            name='tax_ht',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 11)),
        ),
    ]
