# Generated by Django 5.1 on 2024-12-12 13:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0005_localfacture_tax_ht_alter_facture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfacture',
            name='net_pay',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localfacture',
            name='total_ttc',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 12)),
        ),
    ]
