# Generated by Django 5.1 on 2024-12-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0006_localfacture_net_pay_localfacture_total_ttc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='total_payment_after_tax',
        ),
    ]
