# Generated by Django 5.1 on 2024-12-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0007_remove_facture_total_payment_after_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfacture',
            name='identification_number',
        ),
        migrations.AlterField(
            model_name='facture',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='factures',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
