# Generated by Django 5.1 on 2024-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0010_alter_facture_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='address',
        ),
        migrations.AddField(
            model_name='worldfacture',
            name='address',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
