# Generated by Django 5.1 on 2024-12-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0011_remove_facture_address_worldfacture_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='localfacture',
            name='total_sum_fr',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldfacture',
            name='total_sum_en',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
