# Generated by Django 5.1 on 2024-12-13 00:00

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0012_localfacture_total_sum_fr_worldfacture_total_sum_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldfacture',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worldfacture',
            name='firm_name',
        ),
        migrations.AddField(
            model_name='facture',
            name='address',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='firm_name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 13)),
        ),
    ]
