# Generated by Django 5.1 on 2024-12-17 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0013_remove_worldfacture_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localfacture',
            name='net_pay',
        ),
        migrations.AddField(
            model_name='facture',
            name='net_pay',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worldfacture',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 17)),
        ),
    ]
