# Generated by Django 5.1 on 2024-12-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0014_remove_localfacture_net_pay_facture_net_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldfacture',
            name='description',
        ),
        migrations.AddField(
            model_name='worldfacture',
            name='shipping_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
