# Generated by Django 5.1 on 2024-12-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facture', '0015_remove_worldfacture_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldfacture',
            name='description',
            field=models.CharField(default='Recharge Card and Express', max_length=255),
        ),
    ]
