# Main events configuration block
events {
    worker_connections 1024;
}

# Main HTTP configuration block
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Server for HTTPS
    server {
        listen 443 ssl;
        server_name pmsolution-facture.org;

        # SSL Certificate Paths
        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:HIGH:!aNULL:!MD5:!RC4';
        ssl_prefer_server_ciphers on;

        # Proxy to Django application
        location / {
            proxy_pass http://excalibur:8000;  # Proxy to your Django app
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }
    }

    # HTTP server block - Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name pmsolution-facture.org;

        # Certbot challenge path
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/html;
            try_files $uri =404;
        }

        # Redirect all HTTP traffic to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }
}
