# Main events configuration block
events {
    worker_connections 1024;  # Adjust as needed for the number of worker connections
}

# Main HTTP configuration block
http {
    # Include default MIME types
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Log files
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # HTTP server block - Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name pmsolution-facture.org;


        # Allow access to the .well-known directory for Certbot challenges
        location /.well-known/acme-challenge/ {
            root /var/www/html;
            try_files $uri $uri/ =404;
            access_log /var/log/nginx/acme-challenge-access.log;
            error_log /var/log/nginx/acme-challenge-error.log;
        }
        # Redirect all other HTTP traffic to HTTPS
        return 301 https://$host$request_uri;
    }

    # HTTPS server block
}
