"""
Django settings for excalibur project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import sentry_sdk
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-your-secret-key')

# Initialize Sentry only once, adjust the settings based on the environment.
sentry_sdk.init(
    dsn='https://3a19edee45f9812bff566cc93a4fbb52@o4506701381042176.ingest.us.sentry.io/4508597688991744',
    traces_sample_rate=1.0,  # Capture 100% of transactions
    send_default_pii=True,  # Include personally identifiable information (PII) in the event payload
    _experiments={
        'continuous_profiling_auto_start': True,  # Start the profiler automatically when possible
    },
)

# SECURITY WARNING: don't run with debug turned on in production!


LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
    # Add more languages here
]
LANGUAGE_CODE = 'en'
USE_I18N = True
LOCALE_PATHS = [
    BASE_DIR / 'locale',  # Path for storing translation files
]
LANGUAGE_COOKIE_NAME = 'django_language'

ALLOWED_HOSTS = [
    'pmsolution-facture.org',
    'www.pmsolution-facture.org',
    'localhost',
    '127.0.0.1',
    '66.29.142.34',
    '0.0.0.0',
]
INTERNAL_IPS = [
    '127.0.0.1',  # Localhost
    '172.17.0.1',  # Default Docker gateway (adjust if using a custom network)
]

# Application definition
LOGIN_REDIRECT_URL = 'main:main_menu'
LOGOUT_REDIRECT_URL = 'users:login'
LOGIN_URL = 'users:login'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'axes',
    'apps.main',
    'apps.deduction',
    'apps.facture',
    'apps.users',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/usr/src/app/logs/django.log',  # Ensure this path is correct
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'WARNING',
            'handlers': ['console', 'file'],
            'propagate': False,
        },
    },
}
AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesStandaloneBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]
MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 10
CACHE_MIDDLEWARE_KEY_PREFIX = 'excalibur'

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,
}

ROOT_URLCONF = 'excalibur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'excalibur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'pmsolution_facture'),
        'USER': os.getenv('POSTGRES_USER', 'default_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'default_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'database'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
}
CACHES = {
    'default': {
        # 'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        # ! uncomment dummyCache for debug sql queries
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        'LOCATION': 'redis://redis:6379',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

HOME_TEMPLATES = [
    os.path.join(BASE_DIR, 'facture', 'templates'),
    os.path.join(BASE_DIR, 'deduction', 'templates'),
    os.path.join(BASE_DIR, 'users', 'templates'),
    os.path.join(BASE_DIR, 'main', 'templates'),
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/


TIME_ZONE = 'UTC'


USE_TZ = True

SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ENVIRONMENT = os.getenv('ENVIRONMENT', 'production')


if ENVIRONMENT == 'production':
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    DEBUG = False
else:
    # Disable SSL redirection for development (no need for SSL)
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = None
    DEBUG = True

if not DEBUG:
    # For production, Sentry should be properly configured with performance monitoring.
    sentry_sdk.init(
        dsn='https://3a19edee45f9812bff566cc93a4fbb52@o4506701381042176.ingest.us.sentry.io/4508597688991744',
        traces_sample_rate=1.0,
        send_default_pii=True,
        _experiments={
            'continuous_profiling_auto_start': True,  # Start the profiler automatically when possible
        },
    )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
