# Generated by Django 5.1.4 on 2024-12-24 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                (
                    'number_deduction',
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ('ifn', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('supplier', models.CharField(max_length=200)),
                (
                    'nature_of_products',
                    models.CharField(
                        blank=True,
                        default='ACHAT PRESTATIONS DE SERV',
                        max_length=150,
                        null=True,
                    ),
                ),
                ('montant_ttc', models.FloatField(blank=True, null=True)),
                ('montant_ht', models.FloatField(blank=True, null=True)),
                ('taux_tva', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('montant_tva', models.FloatField(blank=True, null=True)),
                (
                    'prorated_rate',
                    models.CharField(blank=True, default='', max_length=20, null=True),
                ),
                ('date_regulations', models.DateField(default=django.utils.timezone.now)),
                ('payment_choice', models.CharField(blank=True, max_length=250, null=True)),
                ('cr', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ice', models.TextField(blank=True, null=True)),
                (
                    'owner',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
