# Generated by Django 5.1 on 2024-08-11 19:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('number_facture', models.CharField(max_length=50)),
                ('ifn', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('supplier', models.CharField(max_length=200)),
                ('nature_of_products', models.CharField(blank=True, default='ACHAT PRESTATIONS DE SERV', max_length=150, null=True)),
                ('montant_ttc', models.FloatField(blank=True, null=True)),
                ('montant_ht', models.FloatField(blank=True, null=True)),
                ('taux_tva', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('code_tva', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('montant_tva', models.FloatField(blank=True, null=True)),
                ('prorated_rate', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('date_regulations', models.DateField(default=datetime.datetime.today)),
                ('payment_choice', models.CharField(blank=True, max_length=250, null=True)),
                ('cr', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ice', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
