# Generated by Django 5.1.4 on 2024-12-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduction', '0002_rename_deductions_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
