# Generated by Django 5.1.4 on 2024-12-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduction', '0003_deduction_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='ice',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
