# Generated by Django 5.1.4 on 2024-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deduction', '0004_alter_deduction_ice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='prorated_rate',
            new_name='proporated_rate',
        ),
    ]
