name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:17
        ports:
          - 5434:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: |
          --network-alias database

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - "5672:5672"
          - "15672:15672"
        env:
          RABBITMQ_DEFAULT_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_DEFAULT_PASS: ${{ secrets.RABBITMQ_PASSWORD }}
        options: |
          --network-alias rabbitmq
          --health-cmd "curl -f http://localhost:15672/healthcheck || exit 1"
          --health-interval 10s
          --health-retries 5

    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify environment variables
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}"
          echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}"
          echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}"
          echo "RABBITMQ_QUEUE_LOCAL_FACTURE=${{ secrets.RABBITMQ_QUEUE_LOCAL_FACTURE }}"
          echo "RABBITMQ_QUEUE_WORLD_FACTURE=${{ secrets.RABBITMQ_QUEUE_WORLD_FACTURE }}"
          echo "RABBITMQ_QUEUE_DEDUCTIONS=${{ secrets.RABBITMQ_QUEUE_DEDUCTIONS }}"

      - name: Set up environment variables for Sentry
        run: |
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "DEBUG=False" >> $GITHUB_ENV  # Make sure DEBUG is set to False in production

      - name: Build and start containers with docker-compose
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --build

      - name: Wait for PostgreSQL
        run: |
          until docker-compose exec -T database pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Wait for RabbitMQ
        run: |
          until docker-compose exec -T rabbitmq curl -s -f http://localhost:15672/healthcheck; do
            echo "Waiting for RabbitMQ..."
            sleep 5
          done

      - name: Run Django migrations
        run: |
          docker-compose exec -T excalibur python manage.py migrate --noinput

      - name: Run tests
        run: |
          docker-compose exec -T excalibur pytest

      - name: Shutdown services
        run: |
          docker-compose down --remove-orphans
          docker network prune -f  # Force remove any unused networks
