name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:17
        ports:
          - 5434:5432
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: |
          --network-alias database

    steps:
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify environment variables
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"

      - name: Build and start containers with docker-compose
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --build

      - name: Debug Database Logs
        run: docker logs $(docker ps -aq --filter "name=postgres")

      - name: Wait for PostgreSQL
        run: |
          until docker-compose exec -T database pg_isready -U ${{ secrets.POSTGRES_USER }} -d ${{ secrets.POSTGRES_DB }}; do
            echo "Waiting for database..."
            sleep 5
          done

      - name: Run Django migrations
        run: |
          docker-compose exec excalibur python manage.py migrate --noinput

      - name: Run tests
        run: |
          docker-compose exec excalibur python manage.py test --noinput

      - name: Shutdown services
        run: docker-compose down
